# Generated by Django 4.0.5 on 2023-09-25 12:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_username_field_user_username'),
        ('projects', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partner',
            name='userID',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
