# Generated by Django 4.0.5 on 2023-09-25 12:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0002_alter_partner_userid'),
    ]

    operations = [
        migrations.AddField(
            model_name='county',
            name='country',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.country'),
            preserve_default=False,
        ),
    ]
