# Generated by Django 4.0.5 on 2023-09-25 13:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_rename_username_field_user_username'),
        ('projects', '0003_county_country'),
    ]

    operations = [
        migrations.RenameField(
            model_name='member',
            old_name='groupId',
            new_name='group',
        ),
        migrations.RemoveField(
            model_name='group',
            name='languageId',
        ),
        migrations.RemoveField(
            model_name='group',
            name='projectId',
        ),
        migrations.RemoveField(
            model_name='groupleader',
            name='groupId',
        ),
        migrations.RemoveField(
            model_name='groupleader',
            name='memberId',
        ),
        migrations.RemoveField(
            model_name='partner',
            name='userID',
        ),
        migrations.RemoveField(
            model_name='projectsubcategory',
            name='projectCategoryId',
        ),
        migrations.AddField(
            model_name='group',
            name='language',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.language', verbose_name='Language'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='group',
            name='project',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupleader',
            name='group',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.group', verbose_name='Group'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='groupleader',
            name='member',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.member', verbose_name='Member'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='partner',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='user'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectsubcategory',
            name='projectCategory',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory', verbose_name='project Category'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='country',
            name='countryName',
            field=models.CharField(default='Kenya', max_length=40, verbose_name='country Name'),
        ),
        migrations.AlterField(
            model_name='county',
            name='countyName',
            field=models.CharField(max_length=30, verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupName',
            field=models.CharField(max_length=255, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='languageName',
            field=models.CharField(max_length=255, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberAge',
            field=models.IntegerField(verbose_name='Age'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberCategory',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberGender',
            field=models.CharField(max_length=10, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberOccupation',
            field=models.CharField(max_length=255, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membersEmail',
            field=models.EmailField(max_length=254, verbose_name='Email'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membersFirstName',
            field=models.CharField(max_length=255, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membersLastName',
            field=models.CharField(max_length=255, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membersPhone',
            field=models.CharField(max_length=20, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='partner',
            name='organizationName',
            field=models.CharField(max_length=255, verbose_name='organization'),
        ),
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.partner', verbose_name='Partner'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectAnthem',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Anthem'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectCategory',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.projectcategory', verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectCountry',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.country', verbose_name='Country'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectCounty',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.county', verbose_name='County'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectEndDate',
            field=models.DateField(verbose_name='End Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectGroupNo',
            field=models.IntegerField(verbose_name='Group No'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=255, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectStartDate',
            field=models.DateField(verbose_name='Start Date'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectTheme',
            field=models.FileField(blank=True, null=True, upload_to='', verbose_name='Theme'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectZone',
            field=models.CharField(max_length=255, verbose_name='Zone'),
        ),
        migrations.AlterField(
            model_name='projectcategory',
            name='projectcategoryName',
            field=models.CharField(max_length=80, verbose_name='Project Category'),
        ),
        migrations.AlterField(
            model_name='projectofficer',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project', verbose_name='Project'),
        ),
        migrations.AlterField(
            model_name='projectofficer',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user', verbose_name='User'),
        ),
        migrations.AlterField(
            model_name='projectsubcategory',
            name='projectSubcategoryName',
            field=models.CharField(max_length=80, verbose_name='project Sub category'),
        ),
    ]
