# Generated by Django 4.0.5 on 2023-09-25 16:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0005_alter_partner_user_alter_projectofficer_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='memberCategory',
            field=models.CharField(choices=[('Member', 'Member'), ('Leader', 'Leader')], default='Member', max_length=255, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberGender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=10, verbose_name='Gender'),
        ),
    ]
