# Generated by Django 4.0.5 on 2023-09-25 16:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0006_alter_member_membercategory_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectMode',
            field=models.CharField(choices=[('Open', 'Open'), ('Modular', 'Modular')], default='Open', max_length=10, verbose_name='Learning Mode'),
        ),
        migrations.AlterField(
            model_name='group',
            name='groupName',
            field=models.CharField(max_length=40, verbose_name='Group Name'),
        ),
        migrations.AlterField(
            model_name='language',
            name='languageName',
            field=models.CharField(max_length=30, verbose_name='Language'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberCategory',
            field=models.CharField(choices=[('Member', 'Member'), ('Leader', 'Leader')], default='Member', max_length=6, verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberGender',
            field=models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Gender'),
        ),
        migrations.AlterField(
            model_name='member',
            name='memberOccupation',
            field=models.CharField(max_length=30, verbose_name='Occupation'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membersFirstName',
            field=models.CharField(max_length=30, verbose_name='First Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membersLastName',
            field=models.CharField(max_length=30, verbose_name='Last Name'),
        ),
        migrations.AlterField(
            model_name='member',
            name='membersPhone',
            field=models.CharField(max_length=13, verbose_name='Phone Number'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectName',
            field=models.CharField(max_length=80, verbose_name='Project Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectZone',
            field=models.CharField(max_length=40, verbose_name='Zone'),
        ),
    ]
