# Generated by Django 4.0.5 on 2023-09-25 17:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0007_project_projectmode_alter_group_groupname_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='projectSubcategory',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.projectsubcategory', verbose_name='Project Sub Category'),
        ),
    ]
