# Generated by Django 4.0.5 on 2023-09-26 13:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0008_project_projectsubcategory'),
    ]

    operations = [
        migrations.CreateModel(
            name='Channel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channelName', models.CharField(default='Nairobi & Environs', max_length=255, verbose_name='Channel Name')),
                ('channel', models.IntegerField(choices=[(1, 'Channel 1'), (2, 'Channel 2'), (3, 'Channel 3'), (4, 'Channel 4'), (5, 'Channel 5'), (6, 'Channel 6'), (7, 'Channel 7'), (8, 'Channel 8'), (9, 'Channel 9'), (10, 'Channel 10'), (11, 'Channel 11'), (12, 'Channel 12')])),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('radius', models.IntegerField(verbose_name='Channel Radius')),
            ],
        ),
        migrations.AlterField(
            model_name='project',
            name='partner',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.partner', verbose_name='Partner Name'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectAnthem',
            field=models.URLField(blank=True, null=True, verbose_name='Anthem'),
        ),
        migrations.AlterField(
            model_name='project',
            name='projectTheme',
            field=models.URLField(blank=True, null=True, verbose_name='Theme'),
        ),
        migrations.AddField(
            model_name='project',
            name='channel',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='projects.channel', verbose_name='Partner Name'),
            preserve_default=False,
        ),
    ]
