# Generated by Django 4.0.5 on 2023-09-26 13:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0009_channel_alter_project_partner_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.channel', verbose_name='Partner Name'),
        ),
    ]
