# Generated by Django 4.1.7 on 2023-09-26 18:50

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0010_alter_project_channel'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='latitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='member',
            name='location',
            field=django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326),
        ),
        migrations.AddField(
            model_name='member',
            name='longitude',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
