# Generated by Django 4.1.7 on 2023-09-27 06:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0011_member_latitude_member_location_member_longitude'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='channel',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='projects.channel', verbose_name='Channel'),
        ),
    ]
