# Generated by Django 3.2 on 2023-10-06 12:33

import django.contrib.gis.db.models.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0012_alter_project_channel'),
    ]

    operations = [
        migrations.CreateModel(
            name='UngroupedMember',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('membersFirstName', models.CharField(max_length=30, verbose_name='First Name')),
                ('membersLastName', models.CharField(max_length=30, verbose_name='Last Name')),
                ('membersEmail', models.EmailField(max_length=254, verbose_name='Email')),
                ('membersPhone', models.CharField(max_length=13, verbose_name='Phone Number')),
                ('memberGender', models.CharField(choices=[('Male', 'Male'), ('Female', 'Female')], max_length=6, verbose_name='Gender')),
                ('memberAge', models.IntegerField(verbose_name='Age')),
                ('memberOccupation', models.CharField(max_length=30, verbose_name='Occupation')),
                ('memberCategory', models.CharField(choices=[('Member', 'Member'), ('Leader', 'Leader')], default='Member', max_length=6, verbose_name='Category')),
                ('latitude', models.CharField(blank=True, max_length=20, null=True)),
                ('longitude', models.CharField(blank=True, max_length=20, null=True)),
                ('location', django.contrib.gis.db.models.fields.PointField(blank=True, null=True, srid=4326)),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.language', verbose_name='Language')),
            ],
        ),
        migrations.RemoveField(
            model_name='project',
            name='channel',
        ),
        migrations.AddField(
            model_name='project',
            name='grouped',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='project',
            name='levelFiveCategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='levelFourCategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='levelSixCategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='levelThreeCategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.DeleteModel(
            name='Channel',
        ),
        migrations.AddField(
            model_name='ungroupedmember',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='projects.project'),
        ),
    ]
