# Generated by Django 4.1.7 on 2023-09-27 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StatLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project', models.CharField(blank=True, max_length=80, null=True)),
                ('partner', models.CharField(blank=True, max_length=80, null=True)),
                ('Subcategory', models.CharField(blank=True, max_length=80, null=True)),
                ('Country', models.CharField(blank=True, max_length=80, null=True)),
                ('County', models.CharField(blank=True, max_length=80, null=True)),
                ('Zone', models.CharField(blank=True, max_length=40, null=True)),
                ('StartDate', models.DateField(blank=True, null=True)),
                ('EndDate', models.DateField(blank=True, null=True)),
                ('GroupNo', models.IntegerField(blank=True, null=True)),
                ('Mode', models.CharField(blank=True, max_length=10, null=True)),
                ('channel', models.CharField(blank=True, max_length=14, null=True)),
                ('messageTitle', models.CharField(blank=True, max_length=255, null=True)),
                ('Topic', models.CharField(blank=True, max_length=50, null=True)),
                ('SubTopic', models.CharField(blank=True, max_length=70, null=True)),
                ('Length', models.IntegerField(blank=True, null=True)),
                ('Type', models.CharField(blank=True, max_length=10, null=True)),
                ('language', models.CharField(blank=True, max_length=10, null=True)),
                ('dateuploaded', models.DateTimeField(auto_now_add=True)),
                ('group', models.CharField(blank=True, max_length=20, null=True)),
                ('Gender', models.CharField(blank=True, max_length=6, null=True)),
                ('Age', models.CharField(blank=True, max_length=3, null=True)),
                ('Occupation', models.CharField(blank=True, max_length=20, null=True)),
                ('Category', models.CharField(blank=True, max_length=20, null=True)),
                ('latitude', models.CharField(blank=True, max_length=8, null=True)),
                ('longitude', models.CharField(blank=True, max_length=8, null=True)),
            ],
        ),
    ]
