# Generated by Django 3.2 on 2023-10-06 12:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='statlog',
            name='levelFiveCategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='statlog',
            name='levelFourCategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='statlog',
            name='levelSixCategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
        migrations.AddField(
            model_name='statlog',
            name='levelThreeCategory',
            field=models.CharField(blank=True, max_length=80, null=True),
        ),
    ]
