# Generated by Django 3.2 on 2023-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_auto_20231006_1233'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.CharField(blank=True, max_length=70, null=True)),
                ('member', models.CharField(blank=True, max_length=70, null=True)),
                ('feedBack', models.TextField(blank=True, max_length=700, null=True, verbose_name='Feedback Text')),
                ('feedbackTime', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
