# Generated by Django 4.0.5 on 2023-09-25 16:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='usagelog',
            old_name='memberId',
            new_name='member',
        ),
        migrations.RenameField(
            model_name='usagelog',
            old_name='messageId',
            new_name='message',
        ),
    ]
