# Generated by Django 4.0.5 on 2023-09-25 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_rename_memberid_usagelog_member_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='message',
            old_name='languageId',
            new_name='language',
        ),
        migrations.RenameField(
            model_name='message',
            old_name='projectId',
            new_name='project',
        ),
        migrations.AlterField(
            model_name='message',
            name='messageLength',
            field=models.IntegerField(verbose_name='Length of message in seconds'),
        ),
        migrations.AlterField(
            model_name='message',
            name='messagefile',
            field=models.CharField(max_length=200, verbose_name='Link To Google Drive Message'),
        ),
    ]
