# Generated by Django 4.0.5 on 2023-09-26 13:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0003_rename_languageid_message_language_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messagefile',
            field=models.URLField(verbose_name='Link To Google Drive Message'),
        ),
    ]
