# Generated by Django 4.1.7 on 2023-09-26 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0004_alter_message_messagefile'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='messageType',
            field=models.CharField(choices=[('video', 'Video'), ('audio', 'Audio'), ('image', 'Image')], max_length=10),
        ),
    ]
