# Generated by Django 4.1.7 on 2023-09-27 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0005_alter_message_messagetype'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usagelog',
            name='endTime',
            field=models.DateTimeField(verbose_name='End Time'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='messageCompleted',
            field=models.BooleanField(default=False, verbose_name='Completed'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='messageLength',
            field=models.IntegerField(verbose_name='Message Length'),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='startTime',
            field=models.DateTimeField(verbose_name='Start Time'),
        ),
    ]
