# Generated by Django 3.2 on 2023-10-06 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('projects', '0013_auto_20231006_1233'),
        ('content', '0006_alter_usagelog_endtime_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Deployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Deployment Name')),
                ('deployment', models.IntegerField(verbose_name='Deployment Number')),
                ('deploymentDate', models.DateTimeField(auto_now_add=True)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='projects.project')),
            ],
        ),
        migrations.RemoveField(
            model_name='message',
            name='project',
        ),
        migrations.AddField(
            model_name='message',
            name='feedback',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageSubTopic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='messageTopic',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='usagelog',
            name='member',
            field=models.CharField(blank=True, max_length=70, null=True),
        ),
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Playlist Name Title')),
                ('playlist', models.IntegerField(verbose_name='Playlist Number')),
                ('deployment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='content.deployment')),
            ],
        ),
        migrations.AddField(
            model_name='message',
            name='playlist',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='content.playlist'),
        ),
    ]
