# Generated by Django 3.2 on 2023-10-19 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0007_auto_20231006_1233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='playlist',
            name='title',
            field=models.CharField(default='Lesson 1', max_length=255, verbose_name='Playlist Name Title'),
        ),
        migrations.DeleteModel(
            name='UsageLog',
        ),
    ]
